# Site
name: "Robopenguins"
title: "Robopenguins"
description: "Project Archive"
meta_description: "Project archive."
logo: 'assets/images/pebguin.png'
favicon: 'assets/images/pebguin.png'
host: https://www.robopenguins.com
# google_analytics: 'UA-12862194-1'
include: ["_pages"]
permalink: /:title/

image_host: 'https://www.robopenguins.com/assets/wp-content/uploads'

# Authors
authors:
  jon:
    name: Jonathan
    display_name: Jonathan
    gravatar: 89f0dac8b097e473f515d5217c0ac989
    description: "Author of Robopenguins"
    web: 'https://www.robopenguins.com/about.html'

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true